- name: Install basic packages
  apt: pkg=fail2ban,ufw state=installed update_cache=true

- name: SSH - Disallow password authentication
  action: lineinfile dest=/etc/ssh/sshd_config regexp="^PasswordAuthentication" line="PasswordAuthentication no" state=present
  notify: restart sshd

- name: Activate firewall
  ufw: state=enabled policy=deny
  when: enable_fw

- name: Firewall - Allow SSH
  ufw: rule=allow name=OpenSSH
  when: enable_fw
