- hosts: webserver:database:appserver
  tasks:
    - name: Install basic packages
      apt: pkg=fail2ban,ufw state=installed update_cache=true

- hosts: webserver
  tasks:
    - name: Install nginx
      apt: pkg=nginx state=installed update_cache=true


- hosts: database
  tasks:
    - name: Install PostgreSQL
      apt: pkg=postgresql-9.5 state=installed update_cache=true


- hosts: appserver
  tasks:
    - name: Install uwsgi
      apt: pkg=uwsgi-plugin-python3 state=installed update_cache=true
