- name: Install nginx
  apt: pkg=nginx state=installed update_cache=true

- name: Creates media directory
  file: path={{ root_dir }}/media state=directory

- name: Creates static directory
  file: path={{ root_dir }}/static state=directory

- name: Copy nginx configuration file
  template: src=default dest=/etc/nginx/sites-available/default
  notify: restart nginx
