- name: Install nginx
  apt: pkg=nginx state=installed update_cache=true

- name: Creates directories
  file:
    path=/home/{{ user }}/static state=directory
    path=/home/{{ user }}/media state=directory

- name: Copy nginx configuration file
  template: src=default.j2 dest=/etc/nginx/sites-available/default
  notify: restart nginx
