- name: Install nginx
  apt: pkg=nginx,python-passlib state=installed update_cache=true

- name: Creates media directory
  file: path={{ root_dir }}/media state=directory

- name: Creates static directory
  file: path={{ root_dir }}/static state=directory

- name: Copy nginx configuration file
  template: src=nginx-site-default dest=/etc/nginx/sites-available/default
  when: not ssl
  notify: restart nginx

- name: Create basic auth user file
  htpasswd: path=/etc/nginx/htpasswd name={{ basic_auth_user }} password={{ basic_auth_password }} owner=root group=www-data mode=0640
  when: basic_auth

# SSL
#- name: Install Let's Encrypt
#  when: ssl

#- name: Install renew cronjob
#  when: ssl

#- name: Generate dhparam file
#  command: openssl dhparam -out /etc/nginx/ssl/dhparam.pem 2048
